id = "cedar"
name = "Cedar"
version = "0.11.0"
schema_version = 1
authors = ["Cathal Mullan <contact@cathal.dev>"]
description = "Cedar language support for Zed"
repository = "https://github.com/DuskSystems/zed-cedar"

[grammars.cedar]
repository = "https://github.com/DuskSystems/tree-sitter-cedar"
path = "cedar"
commit = "89448e765c25175d0bff5d58c9952a6823e5c594"

[grammars.cedarentities]
repository = "https://github.com/DuskSystems/tree-sitter-cedar"
path = "cedarentities"
commit = "89448e765c25175d0bff5d58c9952a6823e5c594"

[grammars.cedarschema]
repository = "https://github.com/DuskSystems/tree-sitter-cedar"
path = "cedarschema"
commit = "89448e765c25175d0bff5d58c9952a6823e5c594"

[language_servers.cedar-language-server]
name = "Cedar Language Server"
languages = ["Cedar", "Cedar Entities", "Cedar Schema"]
