id = "cedar"
name = "Cedar"
version = "0.12.0"
schema_version = 1
authors = ["Cathal Mullan <contact@cathal.dev>"]
description = "Cedar language support for Zed"
repository = "https://github.com/SwornSystems/zed-cedar"

[grammars.cedar]
repository = "https://github.com/SwornSystems/tree-sitter-cedar"
path = "cedar"
commit = "112e886c976951095b43ad91929269f9c1cca17d"

[grammars.cedarentities]
repository = "https://github.com/SwornSystems/tree-sitter-cedar"
path = "cedarentities"
commit = "112e886c976951095b43ad91929269f9c1cca17d"

[grammars.cedarschema]
repository = "https://github.com/SwornSystems/tree-sitter-cedar"
path = "cedarschema"
commit = "112e886c976951095b43ad91929269f9c1cca17d"

[language_servers.cedar-language-server]
name = "Cedar Language Server"
languages = ["Cedar", "Cedar Entities", "Cedar Schema"]
